const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
window.addEventListener('load',()=>setTimeout(()=>document.querySelector('.loader')?.remove(),1550));
const menu=$('.menu'),panel=$('.menu-panel'),close=$('.close'); menu?.addEventListener('click',()=>panel.classList.add('open')); close?.addEventListener('click',()=>panel.classList.remove('open')); $$('.menu-panel a').forEach(a=>a.addEventListener('click',()=>panel.classList.remove('open')));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12}); $$('.reveal').forEach(x=>io.observe(x));
$$('.filter-row button').forEach(btn=>btn.addEventListener('click',()=>{ $$('.filter-row button').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const f=btn.dataset.filter; $$('.project').forEach(p=>p.classList.toggle('hidden',f!=='all'&&p.dataset.cat!==f)); }));
const dot=$('.cursor-dot'),ring=$('.cursor-ring'); window.addEventListener('pointermove',e=>{if(dot){dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';ring.style.left=e.clientX+'px';ring.style.top=e.clientY+'px'}});
$$('a,button,.project').forEach(el=>{el.addEventListener('mouseenter',()=>{if(ring){ring.style.width='58px';ring.style.height='58px'}});el.addEventListener('mouseleave',()=>{if(ring){ring.style.width='35px';ring.style.height='35px'}})});
if(matchMedia('(pointer:fine)').matches){$$('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${y*-5}deg) rotateY(${x*5}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
const sections=$$('main section[id]'), links=$$('.menu-panel a'); const navObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.style.color='');const l=links.find(a=>a.getAttribute('href')==='#'+e.target.id);if(l)l.style.color='var(--red)'}}),{rootMargin:'-40% 0px -50%'}); sections.forEach(s=>navObs.observe(s));
