const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const data={
"CareerPilot AI":{t:"AI-powered career intelligence platform for resume analysis, ATS optimization and career guidance.",x:["Python","FastAPI","AI","JavaScript"],u:"https://github.com/priyanshu18611/careerpilot-ai"},
"EcoSentinel":{t:"IoT-oriented wildlife conservation system with real-time communication and alert logic.",x:["MERN","IoT","Socket.io","JWT"],u:"https://github.com/priyanshu18611/EcoSentinel"},
"Enterprise Sales Analytics":{t:"Sales intelligence and customer analytics workflow using SQL, Python and Power BI.",x:["SQL","Python","Power BI","DAX"],u:"https://github.com/priyanshu18611/enterprise-sales-analytics"},
"Brain Tumor Detection":{t:"MRI image classification project using convolutional neural networks and computer vision.",x:["CNN","TensorFlow","OpenCV","Python"],u:"https://github.com/priyanshu18611/brain-tumor-detection"},
"Cricket Score Predictor":{t:"Machine-learning project for cricket score prediction using structured match data.",x:["Python","XGBoost","Scikit-learn"],u:"https://github.com/priyanshu18611/Cricket-Score-Predictor"},
"Spam Mail Detection":{t:"Machine-learning workflow for detecting spam email using text features and classification.",x:["Python","NLP","TF-IDF","ML"],u:"https://github.com/priyanshu18611/Spam-Mail-Detection"}
};
window.addEventListener("load",()=>setTimeout(()=>$("#boot").remove(),1900));
function tick(){let d=new Date();$("#clock").textContent=d.toLocaleTimeString("en-IN",{hour12:false})}tick();setInterval(tick,1000);
addEventListener("scroll",()=>$("#bar").style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+"%");
$("#hamb").onclick=()=>$("#mobileNav").classList.toggle("open");$$('#mobileNav a').forEach(a=>a.onclick=()=>$("#mobileNav").classList.remove("open"));
$$(".node").forEach(n=>n.onclick=()=>{let p=data[n.dataset.key];$("#dtitle").textContent=n.dataset.key;$("#dtext").textContent=p.t;$("#dtech").innerHTML=p.x.map(v=>`<span class="chip">${v}</span>`).join("");$("#dlink").href=p.u;$("#drawer").classList.add("open")});$("#close").onclick=()=>$("#drawer").classList.remove("open");
$$(".magnetic").forEach(e=>{e.onpointermove=v=>{let r=e.getBoundingClientRect();e.style.transform=`translate(${(v.clientX-r.left-r.width/2)*.1}px,${(v.clientY-r.top-r.height/2)*.1}px)`};e.onpointerleave=()=>e.style.transform=""});
const palette=$("#palette"),search=$("#search"),results=$("#results"),commands=[["Projects","#projects"],["About","#about"],["Engineering Stack","#stack"],["Experience","#experience"],["Contact","#contact"],["Resume","assets/resume/Priyanshu-Kumar-Resume.pdf"],["GitHub","https://github.com/priyanshu18611"],["LinkedIn","https://www.linkedin.com/in/priyanshuroy18"]];
function render(q=""){results.innerHTML=commands.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())).map((x,i)=>`<div class="result" data-i="${i}">${x[0]}</div>`).join("");$$(".result").forEach(r=>r.onclick=()=>{let u=commands[r.dataset.i][1];palette.classList.remove("open");u[0]=="#" ? document.querySelector(u).scrollIntoView({behavior:"smooth"}):window.open(u,"_blank")})}render();
$("#cmd").onclick=()=>{palette.classList.add("open");search.value="";render();setTimeout(()=>search.focus(),20)};search.oninput=e=>render(e.target.value);palette.onclick=e=>{if(e.target===palette)palette.classList.remove("open")};addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()=="k"){e.preventDefault();$("#cmd").click()}if(e.key=="Escape")palette.classList.remove("open")});
const cursor=$("#cursor"),dot=$("#dot");addEventListener("pointermove",e=>{cursor.style.transform=`translate(${e.clientX-12}px,${e.clientY-12}px)`;dot.style.transform=`translate(${e.clientX-2}px,${e.clientY-2}px)`});
if(window.THREE){const c=$("#space"),s=new THREE.Scene(),cam=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);cam.position.z=5;const r=new THREE.WebGLRenderer({canvas:c,alpha:true,antialias:true,powerPreference:"high-performance"});r.setPixelRatio(Math.min(devicePixelRatio,innerWidth<800?1.2:1.7));r.setSize(innerWidth,innerHeight);let n=innerWidth<800?650:1500,p=new Float32Array(n*3);for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,rr=THREE.MathUtils.randFloat(2,10);p[i*3]=Math.cos(a)*rr;p[i*3+1]=Math.sin(a)*rr;p[i*3+2]=(Math.random()-.5)*8}let g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(p,3));let m=new THREE.PointsMaterial({color:0xffffff,size:innerWidth<800?.02:.027,opacity:.5,transparent:true});let stars=new THREE.Points(g,m);s.add(stars);let tx=0,ty=0,mx=0,my=0;addEventListener("pointermove",e=>{tx=(e.clientX/innerWidth-.5)*.6;ty=(e.clientY/innerHeight-.5)*.4});function loop(t){mx+=(tx-mx)*.02;my+=(ty-my)*.02;stars.rotation.y=t*.000018+mx;stars.rotation.x=t*.00001+my;cam.position.x=mx*.35;cam.position.y=-my*.2;cam.lookAt(0,0,0);r.render(s,cam);requestAnimationFrame(loop)}requestAnimationFrame(loop);addEventListener("resize",()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();r.setPixelRatio(Math.min(devicePixelRatio,innerWidth<800?1.2:1.7));r.setSize(innerWidth,innerHeight)})}
let field=$("#constellation"),drag=false,px=0,py=0,rx=0,ry=0;field.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY};addEventListener("pointerup",()=>drag=false);addEventListener("pointermove",e=>{if(!drag)return;ry+=(e.clientX-px)*.08;rx+=(e.clientY-py)*.05;px=e.clientX;py=e.clientY;field.style.transform=`perspective(1100px) rotateX(${rx*.03}deg) rotateY(${ry*.03}deg)`});
