const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
window.addEventListener('load',()=>setTimeout(()=>$('.loader')?.classList.add('done'),1500));
const cursor=$('.cursor');
if(cursor && matchMedia('(pointer:fine)').matches){window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});$$('a,button,.work-card,.tilt').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.style.transform='translate(-50%,-50%) scale(1.7)');el.addEventListener('mouseleave',()=>cursor.style.transform='translate(-50%,-50%) scale(1)')})}
const menu=$('#menu'), mobile=$('#mobileNav');menu?.addEventListener('click',()=>mobile.classList.toggle('open'));$$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});$$('.reveal').forEach(el=>obs.observe(el));
const bar=$('.scrollline i');addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;bar.style.height=(h?scrollY/h*100:0)+'%'});
$$('[data-tilt="true"],.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{if(!matchMedia('(pointer:fine)').matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.classList.add('active');if(card.classList.contains('hero-device'))card.style.transform=`perspective(1200px) rotateY(${(-17+x*10).toFixed(2)}deg) rotateX(${(8-y*10).toFixed(2)}deg) rotateZ(-2deg)`;else card.style.transform=`perspective(900px) rotateX(${(-y*5).toFixed(2)}deg) rotateY(${(x*7).toFixed(2)}deg) translateY(-4px)`});card.addEventListener('pointerleave',()=>{card.classList.remove('active');card.style.transform=card.classList.contains('hero-device')?'perspective(1200px) rotateY(-17deg) rotateX(8deg) rotateZ(-2deg)':''})});
// project folder filters
const buttons=$$('.folder-tabs button'), cards=$$('.work-card');buttons.forEach(btn=>btn.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.textContent.trim().toLowerCase();cards.forEach(card=>{const type=($('.folder',card)?.textContent||'').toLowerCase();const show=f==='all'||type.includes(f.split(' ')[0]);card.style.display=show?'':'none'})}));
// active section label in navigation
const sections=$$('main section[id]');const links=$$('.nav nav a');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}}),{threshold:.35});sections.forEach(s=>io.observe(s));
